version: '3'
services:
  app_insurance:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db_insurance
    ports:
      - 8001:8001
    networks:
      - app_network

  db_insurance:
    image: postgres
    restart: unless-stopped
    volumes:
      - ./_postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    container_name: db_insurance_rates
    ports:
      - 5435:5435
    command: -p 5435
    networks:
      - app_network

networks:
  app_network:
